unstable_features = true
condense_wildcard_suffixes = true
# not compatible with stable
#enum_discrim_align_threshold = 50
# error_on_line_overflow = true
error_on_unformatted = true
# not compatible with stable
#fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_arm_blocks = false
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
# not compatible with stable
#struct_field_align_threshold = 50
# not compatible with stable
#trailing_semicolon = false
use_field_init_shorthand = true
wrap_comments = true
